loopbackio/strong-soap

src/base.js, src/client.js, src/parser/xmlHandler.js, src/server.js, src/soapModel.js
Fixed soapHeader addition for both server and client.
=> Fixed soapHeader addition for both server and client

src/parser/xmlHandler.js, src/server.js, test/server-test.js, test/wsdl/strict/stockquote.wsdl
=> Enabled another set of test cases from server-test.js

src/base.js, src/server.js, test/server-test.js, test/ssl-test.js
=> Enabled more tests from server-test.js

src/parser/wsdl/definitions.js, test/wsdl-test.js
- Fixed code to support for imported wsdl scenario 
- Converted wsdl-test.js to mocha test
=> Fixed support for imported wsdl scenario & converted wsdl-test.js to mocha test

test/server-test.js
fixes for failed cases in server-test.js
=> regression for server-test

example/weather.js, src/client.js, src/http.js, src/parser/element.js, src/parser/wsdl.js, src/parser/wsdl/parameter.js, src/parser/xmlHandler.js, src/server.js, src/soap.js
- Added debug support
- Fixed warning messages
- Fixed weather.js example to accommodate Fault response when Weather service is down.
- Fixes client.js - val type check
- Fixes #20 
- Fixes #26
=> Debug support & fixed warning msgs

intl/tr/messages.json
https://github.com/strongloop-internal/scrum-apex/issues/17
=> Update tr translation file

example/stockquote.js, example/wsdls/stockquote.wsdl
- added stockquote example since weather service is down
- will remove weather example once Readme is updated to remove it's references.
=> add stockquote example

example/stockquote.js, src/parser/xsd/attribute.js
- Fixes issue https://github.com/strongloop/strong-soap/issues/69
- stockquote sample uses local strong-soap code rather than global strong-soap
=> Fix undefined descriptor in attribute

src/parser/wsdl/operation.js
Fix looping logic for Fault array in operation.js. This fixes issue https://github.com/strongloop/strong-soap/issues/71
=> Fix array loop in operation

README.md, soap-stub.js
- Readme changes
- Fixed soap-stub.js to make it usable
@crandmck PTAL
=> Readme changes to use stockquote

.travis.yml, package.json, src/parser/wsdl/operation.js, test/request-response-samples/execFile__valid_xml_generated_on_request_with_complex_type_element_form_default_missing/request.xml, test/request-response-samples/execFile__valid_xml_generated_on_request_with_complex_type_element_form_default_missing/response.xml, test/request-response-samples/execFile__valid_xml_generated_on_request_with_complex_type_element_form_default_qualified/request.xml, test/request-response-samples/execFile__valid_xml_generated_on_request_with_complex_type_element_form_default_qualified/response.xml, test/request-response-samples/execFile__valid_xml_generated_on_request_with_complex_type_element_form_default_unqualified/request.xml, test/request-response-samples/execFile__valid_xml_generated_on_request_with_complex_type_element_form_default_unqualified/response.xml
- connect to https://github.com/strongloop/strong-soap/issues/130
=> fix soap version detection

src/parser/xmlHandler.js, test/request-response-samples/addList__qualified_attrs/request.json, test/request-response-samples/addList__qualified_attrs/request.xml, test/request-response-samples/addList__qualified_attrs/response.json, test/request-response-samples/addList__qualified_attrs/response.xml, test/request-response-samples/addList__qualified_attrs/soap.messages.xsd, test/request-response-samples/addList__qualified_attrs/soap.wsdl
=> make sure attribute descriptors are honored to map json to xml

test/server-client-rpc-test.js
=> Fix Typo: RPC Literal

src/parser/wsdl.js, src/parser/wsdl/operation.js, src/parser/wsdl/parameter.js, src/parser/xsd/schema.js, test/wsdl-parse-test.js, test/wsdl/recursive-schema-import/AccountingUnit.xsd, test/wsdl/recursive-schema-import/Arrangement.xsd, test/wsdl/recursive-schema-import/Authorization.xsd, test/wsdl/recursive-schema-import/BusinessDirectionItem.xsd, test/wsdl/recursive-schema-import/Channel.xsd, test/wsdl/recursive-schema-import/Common.xsd, test/wsdl/recursive-schema-import/Communication.xsd, test/wsdl/recursive-schema-import/Event.xsd, test/wsdl/recursive-schema-import/Infrastructure.xsd, test/wsdl/recursive-schema-import/InfrastructureSOAP.xsd, test/wsdl/recursive-schema-import/InfrastructureSOAPSecurityHeader.xsd, test/wsdl/recursive-schema-import/Location.xsd, test/wsdl/recursive-schema-import/Product.xsd, test/wsdl/recursive-schema-import/ResourceItem.xsd, test/wsdl/recursive-schema-import/TEST.xsd, test/wsdl/recursive-schema-import/TESTAdditionalHeaders.xsd, test/wsdl/recursive-schema-import/TestFunction.xsd, test/wsdl/recursive-schema-import/TestFunctionManagement.wsdl, test/wsdl/recursive-schema-import/TestFunctionManagement.xsd
See https://github.com/strongloop/strong-soap/issues/149
=> fix xsd include/import recursive processing

src/parser/wsdl.js, test/wsdl-parse-test.js
=> fix: add element text value

README.md, src/client.js, src/utils.js, test/client-test.js
=> feat: add promise support for client operations

README.md
I had some issues while trying to reuse the example code. I had to update the following piece of code.
=> fix soap-stub example on README.md

README.md
=> mark all code blocks in readme.md with their respective type

package.json
Dependencies graph: strong-soap@1.12.1 › strong-globalize@3.3.0 › os-locale@2.1.0 › mem@1.1.0
> mem is an optimization technique used to speed up consecutive function calls by caching the result of calls with identical input.
> Affected versions of this package are vulnerable to Denial of Service (DoS) attacks. Old results are not deleted from the cache and could cause a memory leak.`
=> Update` strong-globalize` to v4.1.1

.npmignore, package.json, src/security/WSSecurityCert.js
Fork https://github.com/JoshKaufman/ursa so that we can publish a version that supports Node 10. There have been multiple requests for @JoshKaufman to publish a new release but he hasn't responded yet.
=> Switch to strong-ursa to support Node 10

src/client.js, src/parser/wsdl/operation.js
https://github.com/strongloop/strong-soap/issues/170
=> Support of sending soapAction in v1.2

.github/stale.yml
Add stablebot for this repo using the `stale.yml` reference in https://github.com/strongloop/loopback/blob/master/.github/stale.yml.
=> chore: add stalebot

README.md
fixed formating in README
- No issue link
=> fixed formating in README

.github/ISSUE_TEMPLATE.md, .github/stale.yml, CONTRIBUTING.md, README.md, package-lock.json, package.json
As part of https://github.com/strongloop/loopback-next/issues/7595
I've switched the contribution method for this repo from CLA to DCO. I probably have missed this repo when I was enabling DCO for most of the LoopBack repos.
Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>
=> chore: move repo to loopbackio org

.github/workflows/continuous-integration.yaml, .travis.yml
see: https://github.com/loopbackio/cicd/issues/6
=> ci: pin NPM major version

.travis.yml
=> ci: fix travis

src/parser/wsdl.js, test/wsdl-parse-with-redirect-test.js
Signed-off-by: Elsaid Achraf <60660214+asaid-0@users.noreply.github.com>
Fixes #351 
=> fix: fixed import uri when wsdl request is redirected

.github/workflows/continuous-integration.yaml
It should be part of PR #675. 
=> chore: drop Node.js 16 in CI

src/base.js, src/server.js, test/server-test.js
=> feat: adding option to disable server pretty formatting

.github/workflows/continuous-integration.yaml, package.json
=> chore: update node engines to anything 18 or above
