src/server.js, test/server-client-rpc-test.js, test/wsdl/json_response.wsdl, test/wsdl/strict/stockquoterpc.wsdl
=> Fixed rpc path, added rpc/literal test and fixed a wsdl

src/client.js, src/server.js, test/server-client-document-test.js, test/server-client-rpc-test.js, test/wsdl/strict/doc_literal_test.wsdl, test/wsdl/strict/doc_literal_wrapped_test.wsdl, test/wsdl/strict/rpc_encoded_test.wsdl, test/wsdl/strict/rpc_literal_test.wsdl, test/wsdl/strict/stockquoterpc.wsdl
1)  Fixed Client.js - removed logic to wrap operationName for DocLitWrapped case since the code already does it in another point of execution.
2) Fixed server.js - while calculating outputName, code assumed that there is a 'part' with the name "body" which is incorrect.
3) Added RPC/Literal test with complex type params 
4) Added RPC/Literal test with simple type params
5) Added RPC/encoded test (skipped for now)
6) Added Document/Literal test 
7) Added Document/Lietral-wrapped test
8) Added detail comments for each of the test case above with the actual input/output env
=> Added another set of test cases and fixed issues with server/client code

src/client.js, src/parser/wsdl/binding.js, src/parser/wsdl/operation.js, src/parser/wsdl/parameter.js, src/server.js, test/server-client-document-test.js, test/server-test.js, test/wsdl/strict/doc_literal_wrapped_test.wsdl
- Fixed Fault support which was not working before correctly.
- Added support for multiple faults in a wsdl operation.
- Added test cases for above support.
- Added comments in the code in this execution path.
=> Fixed support for Fault, added support for multiple faults & new tests

src/parser/xmlHandler.js, test/client-test.js, test/server-client-document-test.js, test/server-options-test.js, test/server-test.js
regression errors after checking in request-response-sample
test case fixes
=> fix regression errors for all test cases

example/weather.js, example/xsds.js, src/base.js, src/client.js, src/parser/wsdl.js, src/parser/wsdl/operation.js, src/parser/xmlHandler.js, src/server.js, test/client-test.js, test/request-response-samples-test.js, test/request-response-samples/GetAccountXml__non_xmlns_attributes_should_be_returned/request.xml, test/request-response-samples/GetAccountXml__non_xmlns_attributes_should_be_returned/response.xml, test/request-response-samples/GetNodes__complex_self_referencing/request.xml, test/request-response-samples/GetNodes__complex_self_referencing/response.xml, test/server-client-document-test.js
- Removed wsdl option 'forceSoap12Headers' setting. Added code to figure out if the request, response   
and fault envelope should use soap 1.1 or soap 1.2 based on the binding from the WSDL.
- Fixed request/response/fault path.
- Fixed tests to invoke correct operation if multiple bindings point to same operation.
- Fixed 1.2 to show correct soap 1.2 namespace in request/response/fault.
- Cleanup of examples with minor fixes.
=> Remove and re-implement forceSoap12Headers wsdl option

package.json
fix to add babel as npm prepublish to compile es6
=> add babel script as prepublish

src/parser/element.js, test/client-customHttp-xsdinclude-test.js, test/request-response-samples/SendCDATA__cdata_is_handled_correctly/request.xml, test/request-response-samples/administrate__Complex_json_object_namespace_issue/request.xml, test/server-client-document-test.js, test/server-options-test.js
This is what fixes the namespace problem for the web services I consume. I think it's the right thing to do since the targetNamespace of the schema containing the requests and responses should be used for those too (if they don't specify another one, though).
=> Using targetNamespace of the attribute if present

src/parser/wsdl/operation.js, test/wsdl/strict/doc_literal_wrapped_test.wsdl
Fixes issue #31  Fix is in operation.js where code passes in 'definitions' to describeHeaders() function.
=> 'definitions' not available in describeHeaders () function

src/security/CookieSecurity.js, src/security/index.js
=> * adding CookieSecurity to built-in security methods

example/ntlm.js, package.json, src/client.js, src/http.js, src/security/NTLMSecurity.js, src/security/WSSecurityCert.js, src/security/index.js, src/server.js, src/soap.js
@raymondfeng  PTAL
Please note the way NTLM security object is set to the client - See NTLM.js example under /example directory. NTLM security object is passed in through client option by the caller instead of caller doing client.setSecurity() unlike other security support we have currently. The reason NTLM security object has to be set while creating client itself rather than after client object is created is because for NTLM auth is needed for loading/retrieval of remote wsdl which happens in http.request() method. Other security objects doesn't need to be set during http 'GET' unlike this one. Open to suggestions if we can make it same as other security setting pattern.
=> Initial support for NTLM

src/parser/xmlHandler.js, test/server-client-document-test.js, test/wsdl/strict/doc_literal_test.wsdl, test/wsdl/strict/doc_literal_wrapped_test.wsdl
Current code doesn't read xsi $attribute and $value from JSON input if the element is defined as xsd:anyType. xsd:anyType results without a type in current code which defaults to isSimple=false. 2nd problem is, if the element value is of simple or date type, current code does not add xsi:type to it. Fixed these problems and added 2 test cases to cover these.
=> Proper support for xsi:type  

src/base.js, src/client.js, src/parser/element.js, src/parser/wsdl.js, test/server-client-document-test.js
Supports forceSoapVersion=1.1 or 1.2 which can be passed in as client option to createClient() method. By default the client request is created based on whether wsdl is defined as 1.1 or 1.2. forceSoapVersion=1.1 will let the user to override this. Also added a test case. 
=> support forcing soap version

src/client.js, src/http.js, test/server-client-document-test.js
By default pretty print is 'true' which means the code creates request envelope with new lines and proper indentations etc. However some web services don't accept request env with new lines and indentations. Hence added prettyPrint as client configuration option to make it configurable where user can pass client option as {prettyPrint: false}. 
=> add prettyPrint to client options

package.json, src/parser/wsdl.js
When wsdl imports another wsdl, the code which loads the imported wsdl goes through a different execution path where the NTLMSecurity client option is not available in wsdl options. This PR fixes this issue where wsdl._initializeOptions(..) method initializes NTLMSecurity from client options similar to other client options. @raymondfeng or @deepakrkris PTAL
=> Initialize NTLMSecurity client option to wsdl option

test/client-test.js, test/server-client-document-test.js
This fixes the CI failure in strong-soap due to http port conflict in test cases.
=> CI Fix: assign http port dynamically in client-test.js

Readme.md
This PR just changes `Readme.md` to `README.md`.  This is how all the other repos spell the file, and (more importantly) the documentation uses [a script](https://github.com/strongloop/loopback.io/blob/gh-pages/update-readmes.sh) that assumes the README filename is spelled this way to grab it and include it into the docs.
I also changed the title to `Strong-soap` according to the [README guidelines](http://loopback.io/doc/en/contrib/README-guidelines.html#organization).
@rashmihunt
=> Change capitalization of readme file

src/parser/wsdl/operation.js
Currently type information is missing in rpc/literal case if the part is XSD simple types (int/string etc). This PR fixes this problem. @deepakrkris PTAL
=> Add type information to simple type as well

src/parser/xmlHandler.js
This fixes multiref merging, which was previously throwing `TypeError: Cannot set property '$attributes' of undefined`.
=> Fix multiRef merging

src/parser/wsdl.js, src/parser/xsd/schema.js, test/wsdl-test.js, test/wsdl/xsdinclude/types-without-tns.xsd, test/wsdl/xsdinclude/xsd_include.wsdl
=> allow xsd:include to include a schema without target namespace

src/security/CookieSecurity.js, src/security/index.js, test/security/CookieSecurity.js
=> added cookie security

src/parser/xmlHandler.js, test/request-response-samples/UpdateProfile__correct_namespaces_for_elements_with_base/request.xml, test/request-response-samples/UpdateProfile__correct_namespaces_for_elements_with_base_ignorednamespaces/request.xml, test/request-response-samples/UpdateProfile__correct_ns_context/request.xml, test/request-response-samples/update__complex_extension_with_array_attributes/request.xml, test/wsdl/typeref/request.xml.js
JSON objects might provide properties in different order than the XML
elements. The fix addresses the issue.
This PR is a new implementation of https://github.com/strongloop/strong-soap/pull/99
- connect to #99 
=> fix: make sure xml elements are mapped based the order of xsd

src/parser/wsdl.js, test/wsdl-load-from-memory-test.js, test/wsdl/from-memory/main.wsdl, test/wsdl/from-memory/multipart/main.wsdl, test/wsdl/from-memory/multipart/sub.wsdl, test/wsdl/from-memory/multipart/xsd.xsd, test/wsdl/from-memory/stockquote.wsdl
We discussed with @raymondfeng the idea of being able to load WSDL files from memory into strong-soap (as opposed to from a file system or a url). Reymond suggested making use of the existing loading structure (as used by `WSDL.open(...)` ), which can be described as:
1) Read the contents of the file form the file system/url.
2) Create a WSDL object using the `var wsdl = new WSDL(definition....)` constructor.
3) Perform a `load()` on this object to process the contents of the wsdl, using `wsdl.load(....)`
There are 2 usecases that this PR is aiming to cover.
1) Load a single wsdl file from memory.
2) Load a multipart wsdl (a collection of wsdls and xsd files) from memory.
Usecase 1) could be achieved by the current `strong-soap` functionality, so to achieve this all this PR does it to add …
=> Load WSDL files from the cache

src/soap.js
soap.listen doesn't handle wsdl options like 'attributesKey', etc
PR is a one-line fix for this issue
Question: why is default value for attributesKey for server is 'attributes', not '$attributes'? Found in src/base.js
=> add forgotten options to soap.listen(...)

README.md, src/soap.js, test/client-test.js
Building on the functionality introduced in PR https://github.com/strongloop/strong-soap/pull/168 which allowed for `WSDL` objects to be created from files in memory, this PR allows for a client to be created from a `WSDL` in memory as opposed to just a URL or reference to a file system.
This uses the same idea as is used for creating a `WSDL` i.e. the options that are passed to the client can include a pre-populated cached object called `options.WSDL_CACHE`. If the wsdl is found in  `options.WSDL_CACHE` then it will be used (the client already uses a cache to look for wsdls, it just starts out empty), if not then the current behavior will continue.
https://github.com/strongloop/strong-soap/pull/168
=> Create client from cached wsdl

src/parser/wsdl/types.js, test/wsdl/wsdlImport/sub.wsdl
When trying to create a client from a wsdl which has a `wsdl:documentation` tag under the `wsdl:types` element 
```
<wsdl:types>
<wsdl:documentation>WSDL Documentation example</wsdl:documentation>
<s:schema elementFormDefault="unqualified" targetNamespace="http://www.ibm.com/soap11wsdl" xmlns:s1="http://www.ibm.com/schema1">
...
```
strong-soap failed with the following error:
```
AssertionError [ERR_ASSERTION]: false == true
Expected :true
Actual   :false
<Click to see difference>
at Types.addChild (node_modules\strong-soap\src\parser\wsdl\types.js:14:5)
at Documentation.endElement (node_modules\strong-soap\src\parser\element.js:109:16)
at SAXParser.p.onclosetag (node_modules\strong-soap\src\parser\wsdl.js:299:11)
at emit (node_modules\sax\lib\sax.js:624:35)
at emitNode …
```
=> Allow documentation tag under types

example/xsds.js, src/parser/xsd/element.js
Fix to use proper variable names. Those using complex WSDLs will probably run into this issue with the following error:
```
/Users/badmike/loopback/strong-soap/example/json2xmlwithschema.js:57
].children[1].describe(wsdl.definitions),
^
TypeError: Cannot read property 'children' of undefined
at /Users/badmike/loopback/strong-soap/example/json2xmlwithschema.js:57:9
at /Users/badmike/loopback/strong-soap/src/parser/wsdl.js:105:9
at WSDL._processNextInclude (/Users/badmike/loopback/strong-soap/src/parser/wsdl.js:162:14)
at WSDL.processIncludes (/Users/badmike/loopback/strong-soap/src/parser/wsdl.js:221:10)
at /Users/badmike/loopback/strong-soap/src/parser/wsdl.js:60:12
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback …
```
=> fix: use proper variable names

README.md, src/parser/wsdl.js, test/wsdl-load-from-memory-test.js
Within our product we need the WSDL.load to be called in a sync manner and as this call is async we need an option to be able to call it sync. We will be supplying all wsdls in memory so will not have any I/O.
https://nodejs.org/api/process.html#process_process_nexttick_callback_args
Will use the changes here https://github.com/strongloop/strong-soap/pull/172 to provide all wsdls in memory
**Test run**
File                           |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
Original (master)
wsdl.js                      |       85 |    72.54 |    73.33 |    85.66 |... 72,473,489,490 |
With additional test (forceSyncLoad) 
wsdl.js                      |    85.38 |    73.24 |    73.33 |    86.05 |... …
=> Force sync load

src/parser/xsd/xsdElement.js, test/wsdl-test.js
When using the operation `describe()` function to inspect details of an operation and its elements, the `isMany` property is used to determine if multiple occurrences of an element can be included. Currently if an element looks like `<element maxOccurs="1" minOccurs="0" name="town" type="xsd:string"/>` strong-soap is still setting `isMany` to be true. This should be false as the element says that no more than one instance can be present.
=> Is many logic

package.json
The package that `strong-soap` uses to make NTLM requests (https://www.npmjs.com/package/httpntlm) included a fix in v1.7.6 which addressed an issue with making NTLM requests while using TLS. 
This PR increases the version of `httpntlm` required by strong-soap to make sure that this version is picked up.
=> Update version of httpntlm

src/parser/wsdl.js
options.request was not used when retrieving sub-schemas.
=> Fix use options.request in wsdl.js

src/parser/xmlHandler.js, test/xs-date-format-test.js
Hi,
We found that xs:date elements with Timezone are parsed as null, I did this fix for these cases and tested it locally and works.
However, I tried adding a request-response-sample for unit testing but it doesn't run my code, Can you point me in the right direction to add test coverage for this?
No issues posted
=> Fix for xs:date with tz format

README.md, soap-stub.js
This makes it possible to test when using promise returns on methods instead of just callbacks (no tests needed)
=> Added stubs for testing when using promise returns instead of callbacks

src/parser/xmlHandler.js, test/xs-boolean-format-test.js
Current `xmlHandler` only supports booleans as `true`/`false`. This PR is to add support for `1`/`0` as well.
- connect to #218 
=> Add support for 1/0 booleans

package.json, src/security/WSSecurityCert.js, test/security/WSSecurityCert.js
ursa is an optional binary dependencies and it caused a lot of trouble installing, especially for `loopback-cli`.
This PR replaces ursa with [Node 12 core crypto apis](https://nodejs.org/api/crypto.html) and falls back to [node-rsa](https://github.com/rzcoder/node-rsa).
https://github.com/strongloop/loopback-cli/issues/87
=> Replace ursa with node 12 core crypto or node-rsa

src/http.js, test/client-attachment-test.js
Add support attachments the file
- connect to #185 
=> Add attachments

test/wsdl-parse-test.js
I had a problem to execute the tests. On my windows system, I get a '\r\n' instead the expected '\n'. I think it's a Win-Linux-line-feed-thing...
=> Avoid line feed problems (Win/Linux)

.npmignore
Update `.npmignore` to avoid shipping garbage files to consumers on npm
The largest folder is `coverage`, sitting at 1.8MB.
```
$ du -h -d1 strong-soap/  | sort -h
0       strong-soap/node_modules
4.0K    strong-soap/.vscode
8.0K    strong-soap/.github
60K     strong-soap/example
72K     strong-soap/xsds
120K    strong-soap/intl
432K    strong-soap/lib
440K    strong-soap/src
476K    strong-soap/.nyc_output
1.8M    strong-soap/coverage
3.5M    strong-soap/
```
=> Remove unnecessary files from npm packages

src/parser/xmlHandler.js, test/request-response-samples/Dummy__should_parse_nil/common.xsd, test/request-response-samples/Dummy__should_parse_nil/request.json, test/request-response-samples/Dummy__should_parse_nil/request.xml
Fixes issue with non-string fields (i.e. dates) not being able to be nilled.
#263 
- [x ] New tests added or existing tests modified to cover all changes
- [x ] Code conforms with the [style
=> Allow non strings tobe nillable

src/parser/xmlHandler.js, src/parser/xsd/element.js, src/parser/xsd/restriction.js, src/parser/xsd/simpleType.js, test/client-restrictions-test.js, test/wsdl-test.js, test/wsdl/restriction_anonymous_types.wsdl, test/wsdl/restriction_types.xsd
When specifying the type of an element in an xsd, 2 possible ways are:
1) Specifying the type in the element
```
<xsd:element type="xsd:string" name="elementWithType"/>
```
and 
2) Specifying a restriction via a simple type
```
<xsd:element name="elementWithSimpleType">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="3"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
```
When inspecting the properties of an element using a strong-soap feature like `operation.describe(wsdlDef);` it is possible to find out the type of the first type of element, but not the 2nd type (specified via a restriction).
This PR ensure that this information is set on the describe of the simple type.
A new test has been added to show that the type information is present and there are …
=> Handle restrictions in anonymous simple types

src/client.js, test/client-test.js, test/server-test.js
This PR adds the capability for the internal `_invoke`  method on `client.js`  to parse and add in a clean way soap Headers at run time. We can the property `soapHeaders` to the `options` and `extraHeaders` parameters of this method and it will add it to the soap Headers before calling the remote method.
This will be very helpful especially for loopback 4 soap connector. We can now add the `json` structure to the second or third parameter of the local method in the service.
This relates to the issue 
- connect to https://github.com/strongloop/loopback-connector-soap/issues/108
=> feat add(client) accepts soapHeaders property upon method invocation

package-lock.json, package.json
bump `xml-crypto` to version `2.1.1` that has `xmldom` version `0.1.27` as dependency that has known security vulnerabilities.
=> bump/xml crypto 2.1.1

soap-stub.js
next try - shortening commit message did not really worked, needed to recreated everthing. 
This PR is a replacement to #313 to have only the commit needed to fix the soap-stub.js file.
It adds the accidentally removed require call to globalize.js to allow the stubs createClient() method to be used again for testing
- connect to #313
- connect to 8f28d00
=> add require globalize to fix broken call to g.f()

package-lock.json, package.json, src/http.js
There are 2 changes in this PR:
- Update package-lock.json for `y18n`. The change is generated by running `npm audit fix`.
- replace `httpntlm` with [`httpntlm-maa`](https://github.com/maa105/node-http-ntlm) because of the security vulnerability introduced in one of the dependencies from `httpntlm`. Such vulnerability does not exist in `httpntlm-maa`
=> chore: update dependencies

package-lock.json, package.json, src/http.js, test/client-ntlm-test.js
strong-soap v 3.2.0 updated the NTLM module used from `httpntlm` to `httpntlm-maa`. This module changes the way it behaves based on what other node modules are installed in the dependency tree. Specifically, if `node-fetch` is installed then it will work differently ( https://github.com/maa105/node-http-ntlm/blob/master/httpntlm.js#L59). While `strong-soap` doesn't include, it will continue to see the same behavior as when using the previous `httpntlm` module, any consumer of `strong-soap` who also has `node-fetch` installed in unable to make NTLM requests using strong-soap anymore. 
This PR explicitly specifies that the `request` code path should be taken when using `httpntlm-maa`, thus keeping the same behavior as was seen under the previous module. 
This PR also adds a test case to …
=> NTLM fixes and new tests

README.md
=> Typo in example server code.

README.md
Unfortunately a few PRs and issues fell through the cracks and went stale during the migration to the OpenJS Foundation. This is a re-submission of the original PR with any changes needed to meet the new DCO and CI test requirements.
Original commit author is retained as @luanraithz.
Replaces https://github.com/loopbackio/strong-soap/pull/319
- Code conforms with the [style
=> docs: add `ClientSSLSecurityPFX` to readme

.github/workflows/continuous-integration.yaml, .travis.yml
An unfortunate misspelling caused the Travis CI credits to be used up. ~Once it resets later today (i.e. within 24 hr), I'll re-push this PR to trigger the pipeline and verify its working.~
Contacted Travis and managed to replenish OSS credits.
- Code conforms with the [style
=> ci: fix travis ci arch

.github/workflows/continuous-integration.yaml
see: https://github.com/loopbackio/loopback-next/pull/7867
- Code conforms with the [style
=> ci: restrict GITHUB_TOKEN permissions

package-lock.json, package.json
Signed-off-by: push1st1k <alex060t@gmail.com>
`xml-crypto` library is using `xmldom`, which has vulnerability according to https://www.npmjs.com/advisories/1769. Updating it to the 2.1.3 should solve that issue as a version with a fix (^0.7.0) is using there.
=> chore: bump xml-crypto 2.1.3

package-lock.json, package.json
Signed-off-by: push1st1k <alex060t@gmail.com>
After upgrade to the version 3.3.0 it's not possible to install the library via NPM. The error message is
```
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! .git can't be found (see https://git.io/Jc3F9)
```
The fix is described [here](https://typicode.github.io/husky/#/?id=install-1).
=> fix: fixed installing the library from npm

package.json
The Babel packages `@babel/cli`, `@babel/core` and `@babel/preset-env` are almost always only used at development time, not at run time. Listing them as production dependencies results in a large number of unnecessary packages being installed by downstream consumers. Relegating these to development dependencies *greatly* improves matters for a consumer of `strong-soap`:
* From 301 direct and indirect dependencies down to 116
* From 29.5MB of `node_modules` on disk down to 13.9MB
- None
=> Stop listing Babel as a production dependency

src/server.js, test/server-test.js
Signed-off-by: François Cabrol <fcabrol@spectre-music.com>
If I do a curl to the strong-api route without headers neither body an issue is thrown and is not caught anywhere Invalid value "undefined" for header "Content-Type"
We decided here #375 that the api should return a 415 error.
- connect to #375
=> fix: return a 415 if the call has no Content-Type in the headers

.github/workflows/continuous-integration.yaml
Signed-off-by: dhmlau <dhmlau@ca.ibm.com>
There seems to be an issue to use Node.js 14 when running commit lint GH action. Updating it to use Node.js 16 fixes the issue.
=> chore: use node.js 16 for commit lint GH action

src/parser/xsd/attributeGroup.js, test/wsdl-attributegroup-refs-test.js, test/wsdl/attributegroup_ref.wsdl
Fixed issue in `src/parser/xsd/attributeGroup.js` where the $ref wasn't resolved.
Added test to verify the behaviour with a sample request.
- connect to #526
=> fix: ref in attributeGroup not working

src/parser/xmlHandler.js, test/xs-date-format-test.js
The current version of the library always puts the timezone symbol **Z** at every end of date despite that not all soap services support this date format.
I've extended the `options` parameter for passing the optional `date.timezone` parameter to `XmlHandler` and nested functions for using the optional timezone symbol.
The next code is an example of disabling timezones in the date's string:
```js
const handler = new XMLHandler({}, {
date: {
timezone: {
enabled: false,   
},
});
```
By default `enabled` value is `true` for avoiding breaking changes for the existing API.
- connect to  #289
=> feat: support additional parameter for optional date timezone

src/parser/xmlHandler.js, test/xs-date-format-test.js
Some SOAP services (like the one we're working with) may have a date descriptor but they expect a date in the wrong format, like "23091990"
In this case, the XMLHandler throws an error, but it would be better to just pass the value as is. Adding a try..catch block solves this problem.
=> fix: update xmlHandler.js - try..catch cast to Date

.github/workflows/continuous-integration.yaml, package.json
This PR is considered a breaking change.
=> Align CI config; Drop EOL Node.js versions

src/client.js, test/client-ntlm-test.js, test/client-test.js, test/server-test.js, test/wsdl-test.js
Allowing empty response body case
For #671
=> Allowing empty response body

package.json
According to Node.js LTS schedule, Node.js 16 has reached EOL. 
=> chore: drop Node.js 16 support

README.md, package-lock.json, package.json, src/http.js, test/server-options-test.js, test/server-test.js
Switch from request to @cypress/request so we have no CVE plz
#632
=> fix: resolve CVE-2023-26136

package-lock.json, package.json, src/http.js, test/client-ntlm-test.js
Switches httpntlm-maa to the supported thing.
Fixed the test suite by repairing the bad async bits in the prior test to the reporting test.
=> chore: switch to httpntlm and fix flaky test

.github/workflows/continuous-integration.yaml
Add Node.js 22 to CI, and remove Node.js 21. 
=> chore: add node.js 22 to CI

src/server.js
When adding attributes to the body tag (e.g. ` <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">`), the library currently returns the following error:
> TypeError: Cannot read properties of undefined (reading 'output')
at Server._executeMethod (/usr/src/app/node_modules/strong-soap/src/server.js:337:44)
at Server._process (/usr/src/app/node_modules/strong-soap/src/server.js:207:14)
at IncomingMessage.<anonymous> (/usr/src/app/node_modules/strong-soap/src/server.js:112:18)
at IncomingMessage.emit (node:events:513:28)
at endReadableNT (node:internal/streams/readable:1359:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Currently, this was only supported using the document style and when the attributes key was set to the default …
=> fix: handling attributes on the body tag in the server for both rpc and document styles

package.json
- connect to https://github.com/loopbackio/strong-soap/issues/900
=> chore: add node 22 to engines (#900)
